# Generated by Django 4.2.11 on 2024-05-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_linkedinurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='linkedinurl',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='Unknown', max_length=20, null=True),
        ),
    ]
