# Generated by Django 4.2.11 on 2024-04-26 14:27

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='JobPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('profile', wagtail.fields.RichTextField(blank=True)),
                ('job_type', models.CharField(blank=True, max_length=255)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('experience_level', models.CharField(blank=True, max_length=255)),
                ('education_level', models.CharField(blank=True, max_length=255)),
                ('skills_required', wagtail.fields.RichTextField(blank=True)),
                ('responsibilities', wagtail.fields.RichTextField(blank=True)),
                ('job_company_description', wagtail.fields.RichTextField(blank=True)),
                ('language_requirements', models.CharField(blank=True, max_length=255)),
                ('salary_range', models.CharField(blank=True, max_length=255)),
                ('benefits', wagtail.fields.RichTextField(blank=True)),
                ('work_hours', models.CharField(blank=True, max_length=255)),
                ('remote_work', models.BooleanField(blank=True, default=False)),
                ('travel_requirements', models.CharField(blank=True, max_length=255)),
                ('full_description', wagtail.fields.RichTextField(blank=True)),
                ('contact_information', wagtail.fields.RichTextField(blank=True)),
                ('application_link_email', models.URLField(blank=True)),
                ('how_to_apply', wagtail.fields.RichTextField(blank=True)),
                ('post_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('ex_current_intern_link', models.URLField(blank=True)),
                ('ex_current_linkedin_link', models.URLField(blank=True)),
                ('professional_1_name', models.CharField(blank=True, max_length=255)),
                ('contact_person_1_linkedin', models.URLField(blank=True)),
                ('mail_professional_1', models.EmailField(blank=True, max_length=254)),
                ('contact_person_2_name', models.CharField(blank=True, max_length=255)),
                ('contact_person_2_linkedin', models.URLField(blank=True)),
                ('contact_person_3_name', models.CharField(blank=True, max_length=255)),
                ('contact_person_3_linkedin', models.URLField(blank=True)),
                ('link_linkedin_offer', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
