# Generated by Django 4.2.11 on 2024-04-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpage',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
