# Generated by Django 4.2.11 on 2024-04-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0002_jobpage_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpage',
            name='mail_professional_2',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='jobpage',
            name='mail_professional_3',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
