# Generated by Django 4.2.11 on 2024-05-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0003_jobpage_mail_professional_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpage',
            old_name='professional_1_name',
            new_name='contact_person_1_name',
        ),
    ]
