# Generated by Django 4.2.11 on 2024-05-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0004_rename_professional_1_name_jobpage_contact_person_1_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpage',
            name='contact_person_1_role',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobpage',
            name='contact_person_2_role',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobpage',
            name='contact_person_3_role',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
