# Generated by Django 4.2.11 on 2024-05-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0005_jobpage_contact_person_1_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpage',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
