# Generated by Django 4.2.11 on 2024-05-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0007_jobpage_coding_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpage',
            name='remote_work',
            field=models.BooleanField(default=False),
        ),
    ]
