# Generated by Django 4.2.11 on 2024-05-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0009_alter_jobpage_contact_person_1_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpage',
            name='job_type',
            field=models.CharField(blank=True, choices=[('remote', 'Remote'), ('full time', 'Full Time'), ('part time', 'Part Time')], max_length=255),
        ),
    ]
