# Generated by Django 4.2.11 on 2024-05-22 15:22

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0012_company_alter_jobpage_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpage',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='jobpage',
            name='location',
        ),
        migrations.CreateModel(
            name='JobPageCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joblistings.company')),
                ('job_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_page_companies', to='joblistings.jobpage')),
            ],
        ),
        migrations.CreateModel(
            name='JobPageCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joblistings.city')),
                ('job_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_page_cities', to='joblistings.jobpage')),
            ],
        ),
    ]
