# Generated by Django 4.2.11 on 2024-05-22 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0013_remove_jobpage_company_name_remove_jobpage_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpagecompany',
            name='company',
        ),
        migrations.RemoveField(
            model_name='jobpagecompany',
            name='job_page',
        ),
        migrations.AddField(
            model_name='jobpage',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='joblistings.company'),
        ),
        migrations.AddField(
            model_name='jobpage',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='joblistings.city'),
        ),
        migrations.DeleteModel(
            name='JobPageCity',
        ),
        migrations.DeleteModel(
            name='JobPageCompany',
        ),
    ]
