# Generated by Django 4.2.11 on 2024-05-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0014_remove_jobpagecompany_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpage',
            name='new_company_name',
            field=models.CharField(blank=True, help_text="Add a new company if it's not listed", max_length=255),
        ),
    ]
