# Generated by Django 4.2.11 on 2024-05-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0016_jobpage_new_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpage',
            name='start_date',
            field=models.CharField(blank=True, choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=2, null=True),
        ),
    ]
