# Generated by Django 4.2.11 on 2024-05-23 19:12

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0017_alter_jobpage_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactIntern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('job_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_interns', to='joblistings.jobpage')),
            ],
        ),
    ]
