# Generated by Django 4.2.11 on 2024-05-23 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0019_category_industry_remove_jobpage_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpage',
            old_name='month',
            new_name='start_month',
        ),
    ]
