# Generated by Django 4.2.11 on 2024-05-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0021_currency_remove_jobpage_start_month_jobpage_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoddingLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='currency',
            name='name',
        ),
        migrations.RemoveField(
            model_name='jobpage',
            name='new_currency_name',
        ),
        migrations.RemoveField(
            model_name='jobpage',
            name='coding_languages',
        ),
        migrations.AddField(
            model_name='jobpage',
            name='coding_languages',
            field=models.ManyToManyField(blank=True, to='joblistings.coddinglanguages'),
        ),
    ]
