# Generated by Django 4.2.11 on 2024-05-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0022_coddinglanguages_remove_currency_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobpage',
            name='language_requirements',
        ),
        migrations.AddField(
            model_name='jobpage',
            name='language_requirements',
            field=models.ManyToManyField(blank=True, to='joblistings.languages'),
        ),
    ]
