# Generated by Django 4.2.11 on 2024-05-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0023_languages_remove_jobpage_language_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpage',
            name='new_language_name',
            field=models.CharField(blank=True, help_text="Add a new language if it's not listed", max_length=255),
        ),
    ]
