# Generated by Django 4.2.11 on 2024-05-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0024_jobpage_new_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpage',
            name='expected_salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
